#!/usr/bin/env python3
"""Generate the entity table from CPython's pinned WHATWG entity data.

Pass Lib/html/entities.py from CPython v3.14.0 as the sole argument.
The source SHA-256 is checked before parsing; no source code is executed.
"""

import ast
import hashlib
import pathlib
import sys

SOURCE_SHA256 = "d9c65fb2828dbc1f3e399058a341d51e9375ec5bca95a8e92599c41bd5b78bde"


def main():
    source = pathlib.Path(sys.argv[1]).read_bytes()
    if hashlib.sha256(source).hexdigest() != SOURCE_SHA256:
        raise SystemExit("source does not match CPython v3.14.0 Lib/html/entities.py")
    tree = ast.parse(source)
    table = next(
        ast.literal_eval(node.value)
        for node in tree.body
        if isinstance(node, ast.Assign)
        and any(isinstance(target, ast.Name) and target.id == "html5" for target in node.targets)
    )
    output = [
        "// Generated by scripts/generate_entities.py; do not edit.",
        "// Data: CPython v3.14.0 Lib/html/entities.py (WHATWG named references).",
        "// License: licenses/CPython.txt.",
        "pub(super) static NAMED: &[(&str, &str)] = &[",
    ]
    for name, value in sorted(table.items()):
        escaped = "".join(f"\\u{{{ord(char):x}}}" for char in value)
        output.append(f'    ("{name}", "{escaped}"),')
    output.append("];")
    path = pathlib.Path(__file__).resolve().parents[1] / "crates/astral-html/src/entities_data.rs"
    path.write_text("\n".join(output) + "\n")


if __name__ == "__main__":
    main()
