#!/usr/bin/env python3
"""Generate the entity table from WHATWG's pinned named character references.

Pass the downloaded https://html.spec.whatwg.org/entities.json as the sole argument.
The source SHA-256 is checked before parsing.
"""

import hashlib
import json
import pathlib
import sys
from dataclasses import dataclass, field

SOURCE_SHA256 = "d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6"


@dataclass
class Node:
    children: dict[str, "Node"] = field(default_factory=dict)
    value: str | None = None
    legacy: bool = False


def compact_trie(table):
    """Pack ASCII name paths, preserving terminal prefixes and sorted children."""
    root = Node()
    for name, value in table.items():
        node = root
        for char in name.removesuffix(";"):
            node = node.children.setdefault(char, Node())
        node.value = value
        node.legacy |= not name.endswith(";")

    values = sorted(set(table.values()))
    value_ids = {value: index + 1 for index, value in enumerate(values)}
    labels = ""
    rows = []
    # Breadth-first layout keeps the roots first and each node's children contiguous.
    pending = sorted(root.children.items())
    assert "".join(label for label, _ in pending) == (
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
    )
    for label, node in pending:
        while node.value is None and len(node.children) == 1:
            char, node = next(iter(node.children.items()))
            label += char
        child_start = len(pending)
        pending.extend(sorted(node.children.items()))
        value = value_ids[node.value] if node.value is not None else 0
        if node.legacy:
            value |= 0x8000
        rows.append((len(labels), child_start, value, len(label), len(node.children)))
        labels += label

    assert len(rows) < 65536 and len(labels) < 65536 and len(values) < 32768
    output = [
        "/// Compressed edge: label offset, child offset, value, label length, child count.",
        "///",
        "/// Value zero marks a nonterminal. Otherwise the low 15 bits are a one-based",
        "/// replacement index, and the high bit permits omitting the semicolon.",
        "pub(super) struct NamedNode(pub u16, pub u16, pub u16, pub u8, pub u8);",
        "",
        "/// First 52 nodes are roots for A-Z, then a-z; child ranges are sorted by label.",
        "pub(super) static NODES: &[NamedNode] = &[",
    ]
    output.extend(f"    NamedNode({', '.join(map(str, row))})," for row in rows)
    output.extend(
        [
            "];",
            "",
            f'pub(super) static LABELS: &[u8] = b"{labels}";',
            "",
            "/// UTF-8 byte offset and length of each distinct replacement in VALUE_DATA.",
            "pub(super) static VALUES: &[(u16, u8)] = &[",
        ]
    )
    offset = 0
    for value in values:
        length = len(value.encode("utf-8"))
        output.append(f"    ({offset}, {length}),")
        offset += length
    assert offset < 65536
    output.extend(["];", "", "pub(super) static VALUE_DATA: &str = concat!("])
    for value in values:
        escaped = "".join(f"\\u{{{ord(char):x}}}" for char in value)
        output.append(f'    "{escaped}",')
    output.append(");")
    return output


def main():
    source = pathlib.Path(sys.argv[1]).read_bytes()
    if hashlib.sha256(source).hexdigest() != SOURCE_SHA256:
        raise SystemExit("source does not match the pinned WHATWG entities.json")
    table = {
        name.removeprefix("&"): entry["characters"]
        for name, entry in json.loads(source).items()
    }
    output = [
        "// Generated by scripts/generate_entities.py; do not edit.",
        "// Data: https://html.spec.whatwg.org/entities.json (WHATWG named references).",
        "// License: licenses/WHATWG.txt (BSD-3-Clause).",
        "#[cfg(test)]",
        "pub(super) static NAMED: &[(&str, &str)] = &[",
    ]
    for name, value in sorted(table.items()):
        escaped = "".join(f"\\u{{{ord(char):x}}}" for char in value)
        output.append(f'    ("{name}", "{escaped}"),')
    output.extend(["];", ""])
    output.extend(compact_trie(table))
    path = pathlib.Path(__file__).resolve().parents[1] / "crates/astral-html/src/entities_data.rs"
    path.write_text("\n".join(output) + "\n")


if __name__ == "__main__":
    main()
